FROM ghcr.io/mlflow/mlflow:v2.1.1

# Set the working directory
WORKDIR /mlruns

# Expose the port
EXPOSE 5000

# Copy the mlruns directory to the container
COPY /mlruns /mlruns

# Define the command to run the MLflow UI
CMD ["mlflow", "ui", "--port", "5000", "--host", "0.0.0.0", "--backend-store-uri", "/mlruns", "--artifacts-destination", "/mlruns"]