services:
  mlflow-tracking-server:
    # Build the image from the Dockerfile.Model file
    build:
      context: .
      dockerfile: Dockerfile.Model
      tags:
        - mlflow-tracking-server:latest
        - ghcr.io/b-matos/mlflow-tracking-server:latest
    image: mlflow-tracking-server
    container_name: mlflow-tracking-server
    ports:
      - 5001:5001
    

  default-payment-prediction-service:
    # Build the image from the Dockerfile.Service file
    build:
      context: .
      dockerfile: Dockerfile.Service
      tags:
        - default-payment-prediction-service:latest
        - ghcr.io/b-matos/default-payment-prediction-service:latest
    image: default-payment-prediction-service
    container_name: default-payment-prediction-service
    ports:
      - 5002:5002
    depends_on:
      - "mlflow-tracking-server"

