FROM ghcr.io/mlflow/mlflow:v3.0.0rc0

# Expose the port
EXPOSE 5001

# Copy the mlruns directory to the container
COPY /mlruns /mlruns

# Define the command to run the MLflow UI
CMD ["mlflow", "ui", "--port", "5001", "--host", "0.0.0.0", "--backend-store-uri", "./mlruns", "--artifacts-destination", "./mlruns"]